### ISSUE TITLE
client.rb:376 typo for "referrer"

### ISSUE THREAD

**Issue by mrcook** [jonahb/akismet#4]
The internet made a mistake on the spelling of "referrer" so we need to make sure we always use "referer" instead.

client.rb:376 needs to be updated to `referer: :referer`

**Comment by jonahb** [comment]
No, the Akismet API requires the correct spelling ("referrer"), and I see no reason to use the incorrect spelling in the gem's interface.

See http://akismet.com/development/api/#comment-check

**Comment by mrcook** [comment]
I didn't realise! I thought that was the reason I've been getting the following errors. Do you have any idea where the problem is?


Unexpected error while processing request: Invalid param: referer
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:293:in `block in invoke_comment_method'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:291:in `each'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:291:in `each_with_object'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:291:in `invoke_comment_method'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:192:in `check'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:213:in `spam?'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet.rb:41:in `block in spam?'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:62:in `block in open'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:101:in `open'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet/client.rb:62:in `open'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet.rb:64:in `with_client'
    ruby/gems/2.2.0/gems/akismet-2.0.0/lib/akismet.rb:41:in `spam?'

**Comment by mrcook** [comment]
Ah, I guess that if Akismet requires that spelling then I need to create my params also with that spelling?

**Comment by jonahb** [comment]
Right, the gem uses the spelling "referrer".
